# For production build of ltms-io

name: Production Build of LTMS.io

on:
  push:
    branches: [ master, 808-4-prod-workflow ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: install frontend deps
        run: npm ci
        working-directory: ./frontend/ltms-io

      - name: build frontend
        run: npm run-script build
        working-directory: ./frontend/ltms-io
        env:
          CI: false #TODO: god I hate this I promise this is just for debug
  
  prep-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: install backend deps
        run: npm ci
        working-directory: ./backend

  build-project:
    needs: [build-frontend, prep-backend]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

        #create director if it does not already exist
      - run: mkdir -p production
      - run: cp -R ./backend/* ./production
      - run: cp -R ./frontend/ltms-io/build ./production/frontend