# For production build of ltms-io

name: Production Build of LTMS.io

on:
  push:
    branches: [ master, 808-4-prod-workflow ]

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: install frontend deps
        run: npm ci
        working-directory: ./frontend/ltms-io

      - name: build frontend
        run: npm run-script build
        working-directory: ./frontend/ltms-io
        env:
          CI: false #TODO: god I hate this I promise this is just for debug

        #create director if it does not already exist
      - run: mkdir -p production
      - run: cp -R ./backend/* ./production
      - run: cp -R ./frontend/ltms-io/build ./production/frontend

      - name: Create prod git repo
        run: git init
        working-directory: ./production

      - run: git config user.email "actions@github.com"
        working-directory: ./production

      - run: git config user.name "GitHub Actions"
        working-directory: ./production

      - name: Stage files
        run: git add .
        working-directory: ./production

      - name: Commit files
        run: git commit -m "deploy"
        working-directory: ./production

      - name: Commit remote
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: "ltms-io"
        run: git remote add origin https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
        working-directory: ./production

      - name: Deploy to Heroku
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: "ltms-io"
        if: job.status == 'success'
        run: git push origin master
        working-directory: ./production